name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions-key
          ssh-add -l

      - name: Deploy
        run: |
          ssh -i ~/.ssh/github-actions-key -o StrictHostKeyChecking=no admin@${{ secrets.EC2_HOST }} << 'EOF'
          cd ./TripAdvisor
          git pull origin master
          sudo docker build -t tripadvisor:latest .
          sudo docker stop tripadvisor_app || true
          sudo docker rm tripadvisor_app || true
          sudo docker run -d --name tripadvisor_app -p 5000:5000 tripadvisor:latest

          EOF